Imported Upstream version 0.0+20130624+svn1004

diff --git a/tests/winetricks-test b/tests/winetricks-test
--- a/tests/winetricks-test
+++ b/tests/winetricks-test
@@ -8,7 +8,7 @@ BLACKLIST="cygwin|kde|psdk2003|psdkwin7|dotnet20sp2"
 # verbs that hang in -q because of simple problem we should work around soon
 BLACKLIST="$BLACKLIST|vc2005trial"
 # verbs that are too slow
-BLACKLIST="$BLACKLIST|bfbc2"
+BLACKLIST="$BLACKLIST|bfbc2|dxsdk_nov2006|dxsdk_jun2010"
 # verbs that are too flaky
 BLACKLIST="$BLACKLIST|amnesia_tdd_demo|wowtrial|mfsxde"
 # steam verbs I don't have
@@ -16,14 +16,29 @@ BLACKLIST="$BLACKLIST|borderlands|supermeatboy|trine"
 # broken http://bugs.winehq.org/show_bug.cgi?id=26411:
 BLACKLIST="$BLACKLIST|mfsxde|mfsx_demo"
 # only support older versions of wine
-BLACKLIST="$BLACKLIST|gecko110"
+BLACKLIST="$BLACKLIST|gecko110|gecko"
 # hang lately, probably ui changes in install process
 BLACKLIST="$BLACKLIST|bioshock2|audibledm"
+# We don't have -q support for these
+BLACKLIST="$BLACKLIST|dx8sdk"
+# broken
+BLACKLIST="$BLACKLIST|dotnet11|dotnet11sp1"
+# broken, see https://code.google.com/p/winetricks/issues/detail?id=318
+BLACKLIST="$BLACKLIST|xna40"
+# broken/flaky, http://bugs.winehq.org/show_bug.cgi?id=26016
+BLACKLIST="$BLACKLIST|xmllite"
+# manual downloads
+BLACKLIST="$BLACKLIST|dotnet30|dotnet30sp1|dotnet35|dotnet35sp1"
+# depend on manual downloads
+BLACKLIST="$BLACKLIST|jet40"
+# redundant metaverbs
+BLACKLIST="$BLACKLIST|allcodecs"
+
 
 # Verbs known to update frequently
-QUICKCHECK="flash spotify utorrent utorrent3 hegemonygold_demo"
+QUICKCHECK="flash spotify"
 
-# Check for programs this script (or winetricks) uses.  
+# Check for programs this script (or winetricks) uses.
 # Better to find out they're missing now than in the
 # middle of a two day run.
 for tool in time cabextract unzip 7z
@@ -35,6 +50,7 @@ do
     fi
 done
 
+passes=0
 errors=0
 fail()
 {
@@ -99,9 +115,9 @@ test_app_checksums()
         # Preferably generated under 32-bit wine, so that we don't need a really complex sed
         # substitution here...
         sed -e "s|/Program\ Files/|/$progdir/|" -e "s|/windows/|/$windir/|" < "$srcdir/winetricksverify.d/$app.sha1sum" > $app.sha1sum.tmp
-        if ! sha1sum -c $app.sha1sum.tmp 
+        if ! sha1sum -c $app.sha1sum.tmp
         then
-            fail "test_app_checksum $app !" 
+            fail "test_app_checksum $app !"
         fi
         rm $app.sha1sum.tmp
         cd $srcdir
@@ -117,6 +133,7 @@ total_df()
 test_app()
 {
     app=$1
+    _errors_before=$errors
 
     export WINE_PREFIXES=$HOME/winetrickstest-prefixes
     export WINEPREFIX=$WINE_PREFIXES/$app
@@ -156,11 +173,17 @@ test_app()
     seconds=`awk '/real/ {print $2}' < time.log | sed 's/\..*//'`
     echo "test_app: ${app}: install_time $seconds seconds."
 
-    sh winetricks -q list-installed > list-installed.out
-    if ! grep -w $app list-installed.out
-    then
-        fail "test app $app not installed after install?"
-    fi
+    # Don't check whether metaverbs are installed
+    case "$app" in
+    allcodes) ;;
+    *)
+        sh winetricks -q list-installed > list-installed.out
+        if ! grep -w $app list-installed.out
+        then
+            fail "test app $app not installed after install?"
+        fi
+        ;;
+    esac
 
     # Total max disk usage = max df change plus any initial blocks in cache
     DF_MIN=`cat df-during.log | awk '{ if (min == "" || $1 < min) min=$1; } END {print min}' `
@@ -190,17 +213,23 @@ test_app()
     echo "Wineserver done."
 
     test_app_checksums
+
+    if test $_errors_before = $errors
+    then
+        passes=`expr $passes + 1`
+    fi
 }
 
 test_dlls()
 {
+    sh winetricks list-manual-download > manual.log
     sh winetricks dlls list | awk '{print $1}' > dlls.log
     if grep .------------------- dlls.log
     then
         fail "output of dlls list contained garbage"
         exit 1
     fi
-    sort -u < dlls.log | egrep -v "$BLACKLIST" > dlls.verbs
+    sort -u < dlls.log | fgrep -w -v -f manual.log | egrep -v "$BLACKLIST" > dlls.verbs
     for a in `cat dlls.verbs`
     do
         test_app $a
@@ -238,8 +267,8 @@ test_install_cached_or_download()
         # Split into two, only do half
         nverbs=`cat ticd.verbs | wc -l`
         firsthalf=`expr $nverbs / 2 + 1`
-        sed ${firsthalf}',$d' < ticd.verbs > ticd-1.verbs 
-        sed '1,'${firsthalf}d   < ticd.verbs > ticd-2.verbs 
+        sed ${firsthalf}',$d' < ticd.verbs > ticd-1.verbs
+        sed '1,'${firsthalf}d   < ticd.verbs > ticd-2.verbs
         VERBS=`cat ticd-1.verbs`
     else
         VERBS=`cat ticd.verbs`
@@ -251,7 +280,7 @@ test_install_cached_or_download()
     done
     sh winetricks list-cached | sort > cached.txt
     # Verbs that are just wrappers around others don't detect cache/install
-    # state yet.  
+    # state yet.
     # Verbs that are just informative placeholders don't ever download (gecko).
     # And some verbs (gecko110) don't usually install for other reasons.
     BLACKLIST_CACHE="allfonts|cjkfonts|allcodecs|gecko|gecko110|fontfix"
@@ -270,32 +299,51 @@ test_install_cached_or_download()
     fi
 }
 
-# Test the frequent download-changes-checksum offenders first
-true || (
-cache="$HOME/winetricks-quickcheck-cache"
-rm -rf "$cache"
-export W_CACHE="$cache" 
-for a in $QUICKCHECK
-do
-   rm -rf $HOME/winetrickstest-prefixes/$a
-   test_app $a
-done
-)
+test_quick()
+{
+    # Test the frequent download-changes-checksum offenders first
+    cache="$HOME/winetricks-quickcheck-cache"
+    rm -rf "$cache"
+    export W_CACHE="$cache"
+    for a in $QUICKCHECK
+    do
+       rm -rf $HOME/winetrickstest-prefixes/$a
+       test_app $a
+    done
 
-test_speed list
-test_speed list-download
-# three tries to preload cache
-# FIXME: check cache to see if we need to do this
-for try in `seq 1 3`
-do
-    test_manual_dlls
-    echo press enter
-    read x
-done
-test_dlls
-#test_install_cached_or_download
-test_speed list-cached
-test_speed list-installed
+    # And test all the automatically-downloadable dlls
+    test_dlls
+}
 
-echo "Test over, $errors failures."
-test $errors = 0
+test_full() {
+    test_quick
+    test_speed list
+    test_speed list-download
+    # three tries to preload cache
+    # FIXME: check cache to see if we need to do this
+    for try in `seq 1 3`
+    do
+        test_manual_dlls
+        echo press enter
+        read x
+    done
+    #test_install_cached_or_download
+    test_speed list-cached
+    test_speed list-installed
+}
+
+case "$1" in
+quick) test_quick;;
+full)  test_full;;
+*)     echo "Usage: $0 quick|full"; exit 1;;
+esac
+
+echo "Test over, $errors failures, $passes successes."
+if test $errors = 0 && test $passes -gt 0
+then
+    echo PASS
+    exit 0
+else
+    echo FAIL
+    exit 1
+fi
